### ISSUE TITLE
This project is generally discontinued ?

### ISSUE THREAD

**Issue by goxr3plus** [a-schild/jave2#1]
Hi :) I need to convert any audio format in .mp3 file , is this project discontinued ? How can i do it can i have an example :)

**Comment by a-schild** [comment]
No, this project is alive, but since it's only a wrapper for ffmpeg we don't have much to change on it.

Look at the usage page https://github.com/a-schild/jave2/wiki/Usage
For mp3 as output format, just specify these

File source = new File("source.wav");
File target = new File("target.mp3");
AudioAttributes audio = new AudioAttributes();
audio.setCodec("libmp3lame");
audio.setBitRate(new Integer(128000));
audio.setChannels(new Integer(2));
audio.setSamplingRate(new Integer(44100));
EncodingAttributes attrs = new EncodingAttributes();
attrs.setFormat("mp3");
attrs.setAudioAttributes(audio);
Encoder encoder = new Encoder();
encoder.encode(source, target, attrs);

**Comment by goxr3plus** [comment]
Is there any way to use it with Maven, can it be uploaded on Maven central?
