### ISSUE TITLE
How to set a fixed bit rate

### ISSUE THREAD

**Issue by mumudm** [a-schild/jave2#135]
I want to specify a video bitRate of 1200000, but it keeps floating up and down, which is why and how I should set a fixed bitRate. Help me out here, please!
This is my code.

```
AudioAttributes audio = new AudioAttributes();
audio.setBitRate(info.getAudio().getBitRate());
audio.setChannels(info.getAudio().getChannels());
audio.setSamplingRate(info.getAudio().getSamplingRate());
VideoAttributes video = new VideoAttributes();
video.setCodec("h264");
video.setBitRate(1200000);
VideoSize videoSize = new VideoSize(800, 480);
video.setSize(videoSize);
```

**Comment by a-schild** [comment]
In h264 there is no fixed bitrate, it depends on the video content, how much bandwidth (or bitrate) is required.
The 1200000 is a hint on what bitrate should be targeted by the encoder.

When you have a video with an static image showing, then hte bitrate will be almost 0, since the screen content does not change.
On the other extreme, when every pixel changes it's color to something completely random, then the 1200000 bitrate will not be enough for this and you will see compression artifacts (blocks of the same color)

Why do you need it at exactly the 1200000 bitrate?

**Comment by mumudm** [comment]
On WeChat small program, high bit rate video playback will have lag, so I compressed video bit rate to reduce the playback of lag, I can first I relax this condition a little bit, thank you for reply
