### ISSUE TITLE
Cannot run program "/tmp/jave/ffmpeg-amd64-3.0.1": error=26, Text file busy

### ISSUE THREAD

**Issue by AIAlexander** [a-schild/jave2#238]
Hi, I encountered this error when using a thread pool to parallelly use ffmpeg commands for capturing screenshots from different videos.
Here is Maven:
```xml
<dependency>
     <groupId>ws.schild</groupId>
     <artifactId>jave-all-deps</artifactId>
     <version>3.0.1</version>
</dependency>
```
code:
```java
List<Video> videos = new ArrayList<>;
CountDownLatch latch = new CountDownLatch(videos.size());
Executor executor = CustomExecutor();
for (Video v : videos) {
    executor.run(() -> {
        try {
           ProcessWrapper p = new DefaultFFMPEGLocator().createExecutor();
           p.addArgument("-ss");
           ........
           p.execute();
        } catch(Exception e) {
            e.printStackTrace();
        } finally {
            latch.countDown();
        }
    })
}
```
Is it not allowed to use ffmpeg commands with multiple threads simultaneously?
Thanks for the help!

**Comment by a-schild** [comment]
The code should work concurrently, but I think you are using it incorrectly.

Can you please modify your code, so that 
- you create the `new DefaultFFMPEGLocator()` outside the executor service
- then inside the Executor use the `createExecutor`

Inside the `DefaultFFMPEGLocator` we have a semaphore on the class instance, and when you create multiple `DefaultFFMPEGLocator` instances they won't share the semaphore

**Comment by AIAlexander** [comment]
Thank you! I will try it
