### ISSUE TITLE
Can't use libraries with JDK 7

### ISSUE THREAD

**Issue by b41somp** [a-schild/jave2#33]
Running with >= 2.4.0

It said:

java.lang.UnsupportedClassVersionError: ws/schild/jave/Encoder : Unsupported major.minor version 52.0

Any idea or solution?

**Comment by a-schild** [comment]
In the system requirements it is clearly stated, that JDK 8 is required.

Since JDK 7 is end of support for public users since March 2014 and for comercial users since April 2015, I don't see the need to have new version of jave2 be running on such old releases.

You can try to compile it with jdk 7, perhaps it works...

If you wish, you can provide a pull request which adds jdk 7 coompatibility, so we can have a separate branch for this

**Comment by a-schild** [comment]
Closing due to missing feedback
