### ISSUE TITLE
Big file

### ISSUE THREAD

**Issue by Elikill58** [a-schild/jave2#60]
Hello,

I'm making a lite software, and i want to convert m4a file to mp3 file.
The problem is that the jar is big (around 130MB). And like it's only for a convertion, i think that it's too much.
Can you help me to make the dependencie lighter.

**Comment by a-schild** [comment]
What Plattform are you running?
select the matching nativebin instead of alldeps

**Comment by Elikill58** [comment]
The problem is that i want to make my software compatible for everyone.

**Comment by a-schild** [comment]
The problem is, that we include the ffmpeg executable which does the acutal converion for the 5 supported platforms.
Each binary has a size of (compressed) ~25MB, which then summs up to the total you see.

Perhaps you could provide installers/downloads for the different platforms separately?

I see a option to have a cmbi jar, which works for win32+64 (Would be the 32bit binary).
But for the Linux version, the endusers would have to have the i386 support binaries installed to be able to make the same trick work...

What is your usecase for the library?

**Comment by Elikill58** [comment]
I'm using the library to convert m4a file to mp3.
There is a website to download the good ffmpeg executable or i must to create my own download system ?

**Comment by a-schild** [comment]
It's included in the library, respektive the nativelib ones

**Comment by Elikill58** [comment]
There is a system to download lib when starting program ?

**Comment by Elikill58** [comment]
Yes, i will make a build for each os.
