### ISSUE TITLE
my major.minor version is 51.0,can it be support

### ISSUE THREAD

**Issue by github-big-cheng** [a-schild/jave2#85]
my question is the title

**Comment by a-schild** [comment]
JVM version 51.0 is java version 1.6 which is out of support from sun/oracle since october 2017.

You can make a pull request which adds jvm 1.6 support if you wish, I would then create separate versions for java 1.6.

But it's up to you to make the pull request, since I maintin this project in my free time

**Comment by github-big-cheng** [comment]
Thanks a lot for your reply~

**Comment by robvr** [comment]
> Thanks a lot for your reply~

Found any solution for this issue? I'm facing the same situation

**Comment by github-big-cheng** [comment]
> > Thanks a lot for your reply~
> 
> Found any solution for this issue? I'm facing the same situation

I had choose another way to resolve it ...
